initial code commit
Louis-Dreyfus-Company/geeservermap pull request #2
Opened 2023-04-24 13:26 UTC by rodrigo-ldc

First working and installable version =)

2023-04-26 14:54 UTC, ymesquida submitted a review, later dismissed
SGTM

2023-05-08 10:53 UTC, ymesquida requested changes

2023-05-08 10:53 UTC, ymesquida commented on setup.py
> +    author='LDC Data Sciencie and Remote Sensing team (DSRS)',
Sciencie > Science

2023-05-08 10:53 UTC, ymesquida commented on setup.py
> +    author='LDC Data Sciencie and Remote Sensing team (DSRS)',
@rodrigo-ldc

2023-05-08 12:21 UTC, rodrigo-ldc commented on setup.py
> +    author='LDC Data Sciencie and Remote Sensing team (DSRS)',
thanks =)

2023-05-08 12:44 UTC, ymesquida approved these changes

2023-05-08 12:44 UTC, merged